// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20251105162649_initcreate")]
    partial class initcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("ItemGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemID");

                    b.HasIndex("ItemGroupID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ItemGroup", b =>
                {
                    b.Property<int>("ItemGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemGroupID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemGroupID");

                    b.ToTable("ItemGroups");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shipnote", b =>
                {
                    b.Property<int>("ShipnoteNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipnoteNr"));

                    b.Property<DateOnly>("ShipnoteDate")
                        .HasColumnType("date");

                    b.Property<string>("ShipnoteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("ShipnoteNr");

                    b.HasIndex("StaffID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Shipnotes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ShipnoteLine", b =>
                {
                    b.Property<int>("LineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ShipnoteNr")
                        .HasColumnType("int");

                    b.HasKey("LineID");

                    b.HasIndex("ItemID");

                    b.HasIndex("ShipnoteNr");

                    b.ToTable("ShipnoteLines");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffPhone")
                        .HasColumnType("int");

                    b.Property<string>("StaffPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("SupplierAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierPhone")
                        .HasColumnType("int");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Item", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.ItemGroup", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Supplier", "Supplier")
                        .WithMany("Items")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ItemGroup");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shipnote", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Staff", "Staff")
                        .WithMany("Shipnotes")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Supplier", "Supplier")
                        .WithMany("Shipnotes")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ShipnoteLine", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Item", "Item")
                        .WithMany("ShipnoteLines")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Shipnote", "Shipnote")
                        .WithMany("ShipnoteLines")
                        .HasForeignKey("ShipnoteNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Shipnote");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Item", b =>
                {
                    b.Navigation("ShipnoteLines");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ItemGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shipnote", b =>
                {
                    b.Navigation("ShipnoteLines");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Staff", b =>
                {
                    b.Navigation("Shipnotes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Supplier", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Shipnotes");
                });
#pragma warning restore 612, 618
        }
    }
}
